---
- name: apply common configuration to all nodes
  hosts: all
  user: root

  roles:
    - role: init
      tags: init

    - role: rvm
      rvm1_rvm_version: 'stable'
      rvm1_rvm_check_for_updates: true
      rvm1_rubies:
        # - 'ruby-2.3.1'  ### Set ruby version ###
      rvm1_install_flags: '--auto-dotfiles --user-install'
      rvm1_install_path: "/home/{{ deploy_user }}/.rvm"
      rvm1_user: "{{ deploy_user }}"
      tags: rvm

    - role: backup
      tags: backup

    - role: nginx
      tags: nginx

    - role: postgresql
      tags: postgresql

    - role: redis
      tags: redis

    - role: firewall
      tags: firewall

    - role: monit
      tags: monit
