- name: setup root user
  user:
    name: root
    shell: /bin/bash

- name: create deployer group
  group:
    name: "{{deploy_user}}"

- name: create deployer user
  user:
    name: "{{deploy_user}}"
    shell: /bin/bash
    group: "{{deploy_user}}"
    generate_ssh_key: yes

- name: give deployer user sudo rights
  lineinfile: dest=/etc/sudoers
              state=present
              regexp='^{{deploy_user}} ALL\='
              line='{{deploy_user}} ALL=(ALL) NOPASSWD:ALL'
              validate='visudo -cf %s'

- name: add users ssh keys
  authorized_key:
    user: "{{deploy_user}}"
    key: "{{ item }}"
    state: present
  with_items:
    "{{ ssh_keys }}"

- name: create rvm directory
  file:
    path: /usr/local/rvm
    state: directory
    owner: "{{deploy_user}}"
    recurse: yes
